# Generated by Django 4.0 on 2022-11-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saveAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_Name', models.CharField(max_length=100, null=True)),
                ('Owner_pic', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('House_address', models.TextField()),
                ('Building_img1', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('Room_img1', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('Room_img2', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('Room_img3', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('Landmark', models.TextField()),
                ('House_Location_link', models.URLField(blank=True, null=True)),
                ('House_Location_map', models.CharField(blank=True, max_length=800, null=True)),
                ('House_type', models.CharField(default='2BHK/3BHK/SINGLE', max_length=100)),
                ('AllowedFor', models.CharField(default='All', max_length=100)),
                ('House_description', models.TextField(default='Write something About how good and what are the facilities your renters will get there like electricity/Water etc')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(default='Not Mention', max_length=100)),
                ('location', models.CharField(default='Not Mention', max_length=100)),
                ('pin_no', models.IntegerField()),
                ('Price', models.IntegerField(default=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Premium', models.BooleanField(default=False)),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
    ]
