# Generated by Django 4.0 on 2022-11-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savead',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='savead',
            name='Premium',
        ),
        migrations.AddField(
            model_name='savead',
            name='Alt_phone_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='savead',
            name='phone_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
