# Generated by Django 4.0 on 2022-11-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0002_remove_savead_active_remove_savead_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savead',
            name='House_Location_link',
        ),
        migrations.RemoveField(
            model_name='savead',
            name='House_Location_map',
        ),
        migrations.RemoveField(
            model_name='savead',
            name='location',
        ),
    ]
