# Generated by Django 4.0 on 2022-11-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0003_remove_savead_house_location_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savead',
            name='Landmark',
        ),
    ]
