# Generated by Django 4.0 on 2022-11-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0005_alter_savead_pin_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savead',
            name='Price',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
